### ISSUE TITLE
Failed to start Application (Container Apps)

### ISSUE THREAD

**Issue by v-jiaodi** [pamelafox/flask-surveys-container-app#5]
**Describe the issue:**
1. Test `Local development with Docker`. After `docker-compose up --build` is executed, encountered the following errors：
![image](https://user-images.githubusercontent.com/80496810/220543888-558de80c-fd20-47a3-bd63-0c31bf39307a.png)

2. Test `Deployment`. After the application is deployed, the application url cannot be opened normally. encountered the following errors：

![image](https://user-images.githubusercontent.com/80496810/220556724-5939dc31-96fe-49e9-b417-768165d2a24a.png)

**Repro Steps for issue1:**

1. Run `git clone https://github.com/pamelafox/flask-surveys-container-app.git`.
2. Create an `.env` file by copying `.env.example`.
3. Run command `docker-compose up --build` .

**Repro Steps for issue2:**
1. Run `git clone https://github.com/pamelafox/flask-surveys-container-app.git`.
2. Run command `azd up` .
3. Click deployed service web Endpoint.

**Environment:**
OS: Windows, Devcontainer in VS Code (Windows)
Azd version:  0.6.0-beta.2  (commit https://github.com/Azure/azure-dev/commit/c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Suggestion:**
Through investigation, the reason for this issue is that when clone code to windows, `End of Line` automatically converts from `LF` to `CRLF`. The following are two solutions:
- Option1: Executing `git config --global core.autocrlf false`  before executing `git clone https://github.com/pamelafox/flask-surveys-container-app.git`  can solve these two issues. 
- Option2: Add [.gitattributes](https://git-scm.com/docs/gitattributes) file in template, For example, https://github.com/Azure-Samples/todo-nodejs-mongo/blob/main/.gitattributes

**Expected behavior:**
The application can work normally.

@pamelafox for notification.

**Comment by pamelafox** [comment]
Fascinating, why does the line ending happen to affect the entrypoint.sh script?

I've pushed the suggested change to main, please try again, thanks!

**Comment by v-jiaodi** [comment]
Now this issue no longer exists. I will close it.
